### ISSUE TITLE
Companies Worked With

### ISSUE THREAD

**Issue by Weile-Zheng** [MichiganDataScienceTeam/official-website#80]
In Homepage add a section where we include a list of company names or logos we have worked with in the past (eg. Discover, Bloomberg, Meta ...)

**Comment by izzyg770** [comment]
@sriyan-madugula-um is on this task. let's have it done by wednesday.

**Comment by Weile-Zheng** [comment]
The ones I know are: 
Discover
Bloomberg
Rocket Company
Dominos
PwC.

Reach out to bigpanda@umich.edu for a complete list
