### ISSUE TITLE
Project Card Centering

### ISSUE THREAD

**Issue by danaiamirali** [MichiganDataScienceTeam/official-website#85]
Currently, project cards look odd when the project image dimensions are not perfectly lined up with the card dimensions.

This issue is clearly shown when seeing the difference of the two project cards below:

![image](https://github.com/user-attachments/assets/7d84ca1f-7ac0-4f13-8841-46659772923e)

There is an uncomfortable amount of padding left below the SoccerNet project title due to the image not being tall enough. If we **vertically center the project image/name** in the project card component, that should fix the issue - or at least that is my personal proposal to solve the problem.

---

Also, there is an excessive amount of padding on the right side of the project cards. If we divide the card into two "subfigures" (not sure what the appropriate term is), like shown below, and center the project image/names and the project leads with respect to these "subfigures" that may elevate how everything looks.

![image](https://github.com/user-attachments/assets/5a0aee15-031d-4ec4-8459-d131bece45ee)

For all I know, my proposed changes may be a herculean task - please leave comments down below!

**Comment by Weile-Zheng** [comment]
Good issue!

**Comment by izzyg770** [comment]
i think this should be fixable in the currentProjectCard component (styles section). i won't be able to get to this until monday, so @neeyam-m and @harishj-um, both of you should look at the styles and see if you can fix it before monday morning?

**Comment by harishj-um** [comment]
Pushed changes to `85-project-card-centering`

Old
![image](https://github.com/user-attachments/assets/717bbf5e-19f6-4fd1-bb77-4ddaed2d4e78)

New
![image](https://github.com/user-attachments/assets/9caacaa9-f1ec-4e8d-8ffd-1b3e541c0169)

**Comment by neeyam-m** [comment]
I came up with something a little different:

![image](https://github.com/user-attachments/assets/bbba0280-5c7c-4317-a257-681e27ee5d34)

**Comment by danaiamirali** [comment]
@neeyam-m if you can push your changes that would be great since it seems your modification preserves the rounded edges of the project image.

Is there anything we can do about the project lead icons looking off center?

**Comment by neeyam-m** [comment]
just pushed my version to summer24, the project leads column should also be centered vertically

**Comment by danaiamirali** [comment]
looks great!
